### PR TITLE
Minor fixes in consult-omni-apps and numi

### PR DESCRIPTION
**Pull request by Gleek**

### CODE REVIEW

**Comment by Gleek** [comment]
@armindarvish for your consideration

**Comment by armindarvish** [comment]
@Gleek, Please read [contributions](https://github.com/armindarvish/consult-omni?tab=readme-ov-file#contributions) section in the README. You are supposed to make changes in consult-omni.org and tnagle from that file (and not directly edit the `.el` files!).  

I implemented the changes you suggested separately and merged with main.

**Comment by armindarvish** [comment]
Closing this now since it does not follow the contribution instructions

**Comment by Gleek** [comment]
Understood! Will take care next time. Thanks!

**Pull request closed without merging**
